name: Apple iOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_ios:
    strategy:
      matrix:
        config: [Release, Debug]
      fail-fast: false
    
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: >
        cmake -S . -B ${{github.workspace}}/iOS-arm64
        -DCMAKE_BUILD_TYPE=${{ matrix.config }}
        -DLLGL_BUILD_RENDERER_OPENGLES3=OFF
        -DLLGL_BUILD_RENDERER_METAL=ON
        -DLLGL_BUILD_EXAMPLES=OFF
        -DCMAKE_SYSTEM_NAME=iOS
        "-DCMAKE_OSX_ARCHITECTURES=arm64"
        -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0
        -DCMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH=NO
        -DCMAKE_IOS_INSTALL_COMBINED=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/iOS-arm64 --config ${{ matrix.config }}
      
