name: Apple iOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_ios:
    strategy:
      matrix:
        config: [Release, Debug]
      fail-fast: false
    
    runs-on: macos-latest

    env:
      DEPLOYMENT_TARGET: 13.0

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: >
        cmake -S . -B ${{github.workspace}}/iOS-arm64
        -DCMAKE_SYSTEM_NAME=iOS
        -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
        -DCMAKE_OSX_DEPLOYMENT_TARGET=${{ env.DEPLOYMENT_TARGET }}
        -DCMAKE_IOS_INSTALL_COMBINED=ON
        -DCMAKE_BUILD_TYPE=${{ matrix.config }}
        -DLLGL_BUILD_RENDERER_OPENGLES3=ON
        -DLLGL_BUILD_RENDERER_METAL=ON
        -DLLGL_BUILD_EXAMPLES=OFF

    - name: Build
      run: cmake --build ${{github.workspace}}/iOS-arm64 --config ${{ matrix.config }}
      
